### ISSUE TITLE
Tailwind: CV Page final tunnings

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/raulmelo-dev-web#132]
# Tasks

- [x] Underscore links are black on dark mode
  <img src="https://user-images.githubusercontent.com/12464600/100280076-e4b2eb80-2f67-11eb-9f9d-9fde21a95526.jpeg" width="300" />
- [x] No spacing between skills
  <img src="https://user-images.githubusercontent.com/12464600/100280079-e4b2eb80-2f67-11eb-9a2b-25e87f0511ec.jpeg" width="300" />
- [x] Scroll to top button in wrong bg and color in dark mode
  <img src="https://user-images.githubusercontent.com/12464600/100280081-e54b8200-2f67-11eb-8a7e-b621907ec0df.jpeg" width="300" />
- [x] Back to home isn't clickable on mobile
  <img src="https://user-images.githubusercontent.com/12464600/100280083-e5e41880-2f67-11eb-93a4-29b29f6c9e08.jpeg" width="300" />
